// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/qx66/picMagic/internal/biz"
	"github.com/qx66/picMagic/internal/conf"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initApp(bootstrap *conf.Bootstrap, logger *zap.Logger) (*app, error) {
	pic := biz.NewPic(bootstrap, logger)
	mainApp := newApp(pic)
	return mainApp, nil
}
